### ISSUE TITLE
Error: Ajax error for https://hackmd.io/4er5Ym8SRgigCJR0Ez-t2Q/download : 403

### ISSUE THREAD

**Issue by leo424y** [hbdoy/hackmd_download#1]
<img width="1260" alt="screen shot 2018-08-29 at 11 28 42 pm" src="https://user-images.githubusercontent.com/1384394/44798199-84e00580-abe3-11e8-9742-db0ca8a197d7.png">

https://hackmd.io/4er5Ym8SRgigCJR0Ez-t2Q 這個note
403 Forbidden oh no.

**Comment by hbdoy** [comment]
謝謝回報，忘記考慮到別人的筆記可能設為 private。
45c222e393c938bfa751b7433d72ff149fc66c51
